# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X crules/internal/version.Version={{.Version}}
    binary: crules

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
      - goos: linux
        format: tar.gz
      - goos: darwin
        format: tar.gz

brews:
  - repository:
      owner: nsnarender5511
      name: homebrew-tap
    homepage: https://github.com/nsnarender5511/crules
    description: "A tool for managing and synchronizing Cursor rules across multiple projects"
    license: MIT
    test: |
      system "#{bin}/crules --version"

scoops:
  - repository:
      owner: nsnarender5511
      name: scoop-bucket
    homepage: https://github.com/nsnarender5511/crules
    description: "A tool for managing and synchronizing Cursor rules across multiple projects"
    license: MIT

nfpms:
  - vendor: nsnarender5511
    homepage: https://github.com/nsnarender5511/crules
    maintainer: nsnarender5511
    description: "A tool for managing and synchronizing Cursor rules across multiple projects"
    license: MIT
    formats:
      - deb
      - rpm

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:' 