builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X crules/internal/version.Version={{.Version}}
    binary: crules

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - README.md
      - LICENSE

brews:
  - tap:
      owner: "{{.Env.GITHUB_REPOSITORY_OWNER}}"
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/{{.Env.GITHUB_REPOSITORY}}"
    description: "A tool for managing and synchronizing Cursor rules across multiple projects"
    license: "MIT"
    test: |
      system "#{bin}/crules --version"

scoop:
  bucket:
    owner: "{{.Env.GITHUB_REPOSITORY_OWNER}}"
    name: scoop-bucket
  homepage: "https://github.com/{{.Env.GITHUB_REPOSITORY}}"
  description: "A tool for managing and synchronizing Cursor rules across multiple projects"
  license: MIT

nfpms:
  - vendor: "{{.Env.GITHUB_REPOSITORY_OWNER}}"
    homepage: "https://github.com/{{.Env.GITHUB_REPOSITORY}}"
    maintainer: "{{.Env.GITHUB_REPOSITORY_OWNER}}"
    description: "A tool for managing and synchronizing Cursor rules across multiple projects"
    license: MIT
    formats:
      - deb
      - rpm

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:' 