name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      
      - name: Run tests
        run: go test -v ./...
        
      # Fallback approach if the tests fail due to toolchain issue
      - name: Remove toolchain directive and retry tests (fallback)
        if: failure()
        run: |
          echo "First test attempt failed, trying fallback approach..."
          # Remove toolchain directive and update Go version if needed
          sed -i '/toolchain go1.24.1/d' go.mod
          go mod tidy
          # Run tests again
          go test -v ./...
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest 