name: GoReleaser Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: '1.24'
          cache: true

      - name: Run GoReleaser Check
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: latest
          args: check 